export const ActionTypes = {
  ERROR_LIST_MUSIC: 'ERROR_LIST_MUSIC',
  GET_LIST_MUSIC: 'GET_LIST_MUSIC',
  MORE_LIST_MUSIC: 'MORE_LIST_MUSIC',
  SET_LIST_MUSIC: 'SET_LIST_MUSIC',
  SET_IS_LOADING: 'SET_IS_LOADING',
  SET_FAVORITE_MUSIC: 'SET_FAVORITE_MUSIC',
  SET_SEARCH_MUSIC: 'SET_SEARCH_MUSIC',
  SET_SEARCH_LIST_MUSIC: 'SET_SEARCH_LIST_MUSIC',
  SET_SEARCH_STATE: 'SET_SEARCH_STATE',
  REQUEST_LIST_MUSIC: 'REQUEST_LIST_MUSIC',
};
